const subteData = {
    lines: [
        { id: 'A', name: 'Línea A', color: '#00628a', colorClass: 'bg-line-a', from: 'Plaza de Mayo', to: 'San Pedrito', trains: ['CNR-Citic'] },
        { id: 'B', name: 'Línea B', color: '#bb001d', colorClass: 'bg-line-b', from: 'L. N. Alem', to: 'J. M. de Rosas', trains: ['Mitsubishi', 'CAF 6000'] },
        { id: 'C', name: 'Línea C', color: '#0000ff', colorClass: 'bg-line-c', from: 'Retiro', to: 'Constitución', trains: ['CNR-Citic', 'Nagoya'] },
        { id: 'D', name: 'Línea D', color: '#00a181', colorClass: 'bg-line-d', from: 'Catedral', to: 'Congreso de Tucumán', trains: ['Alstom 100', 'Alstom 300'] },
        { id: 'E', name: 'Línea E', color: '#9b3a97', colorClass: 'bg-line-e', from: 'Retiro', to: 'Plaza de los Virreyes', trains: ['Alstom 100', 'Fiat Materfer'] },
        { id: 'H', name: 'Línea H', color: '#705d00', colorClass: 'bg-line-h', from: 'Facultad de Derecho', to: 'Hospitales', trains: ['Alstom 300'] },
        { id: 'P', name: 'Premetro', color: '#ffcc00', colorClass: 'bg-yellow-400', from: 'Int. Saguier', to: 'Gral. Savio / Centro Cívico', trains: ['Materfer MT-F'] }
    ],
    stations: {
        'A': [
            { name: 'Plaza de Mayo', combinations: ['D', 'E'] },
            { name: 'Perú' },
            { name: 'Piedras', closed: true },
            { name: 'Lima', combinations: ['C'] },
            { name: 'Sáenz Peña' },
            { name: 'Congreso' },
            { name: 'Pasco' },
            { name: 'Alberti' },
            { name: 'Plaza Miserere', combinations: ['H'], train: 'Sarmiento' },
            { name: 'Loria' },
            { name: 'Castro Barros' },
            { name: 'Río de Janeiro' },
            { name: 'Acoyte' },
            { name: 'Primera Junta' },
            { name: 'Puan' },
            { name: 'Carabobo' },
            { name: 'San José de Flores' },
            { name: 'San Pedrito' }
        ],
        'B': [
            { name: 'Leandro N. Alem', combinations: ['E'] },
            { name: 'Florida' },
            { name: 'Carlos Pellegrini', combinations: ['C', 'D'] },
            { name: 'Uruguay' },
            { name: 'Callao' },
            { name: 'Pasteur - AMIA' },
            { name: 'Pueyrredón', combinations: ['H'] },
            { name: 'Carlos Gardel' },
            { name: 'Medrano' },
            { name: 'Ángel Gallardo' },
            { name: 'Malabia - Osvaldo Pugliese', closed: true },
            { name: 'Federico Lacroze', train: 'Urquiza' },
            { name: 'Dorrego' },
            { name: 'Tronador - Villa Ortúzar' },
            { name: 'De los Incas - Parque Chas' },
            { name: 'Echeverría' },
            { name: 'Juan Manuel de Rosas', combinations: [], train: 'Mitre' }
        ],
        'C': [
            { name: 'Retiro', combinations: ['E'], train: 'Mitre/San Martín' },
            { name: 'Gral. San Martín' },
            { name: 'Lavalle' },
            { name: 'Diagonal Norte', combinations: ['B', 'D'] },
            { name: 'Avenida de Mayo', combinations: ['A'] },
            { name: 'Moreno' },
            { name: 'Independencia', combinations: ['E'] },
            { name: 'San Juan' },
            { name: 'Constitución', train: 'Roca' }
        ],
        'D': [
            { name: 'Catedral', combinations: ['A', 'E'] },
            { name: '9 de Julio', combinations: ['B', 'C'] },
            { name: 'Tribunales', closed: true },
            { name: 'Callao' },
            { name: 'Facultad de Medicina' },
            { name: 'Pueyrredón', combinations: ['H'] },
            { name: 'Agüero' },
            { name: 'Bulnes' },
            { name: 'Scalabrini Ortiz' },
            { name: 'Plaza Italia' },
            { name: 'Palermo', train: 'San Martín' },
            { name: 'Ministro Carranza', train: 'Mitre' },
            { name: 'Olleros' },
            { name: 'José Hernández' },
            { name: 'Juramento' },
            { name: 'Congreso de Tucumán' }
        ],
        'E': [
            { name: 'Retiro', combinations: ['C'], info: 'Aquí conectamos con los trenes grandes y la terminal de micros. 🚂' },
            { name: 'Catalinas', info: 'Estación moderna rodeada de oficinas altísimas. 🏢' },
            { name: 'Correo Central', combinations: ['B'], info: 'Ubicada justo debajo del hermoso edificio del CCK. 🏛️' },
            { name: 'Bolívar', combinations: ['A', 'D'], info: '¡Muy cerquita de la histórica Plaza de Mayo!' },
            { name: 'Belgrano', info: 'Sobre la gran Avenida Belgrano, con mucho tránsito.' },
            { name: 'Independencia', combinations: ['C'], info: 'Cruce muy importante cerca de la ancha Av. 9 de Julio. 🚥' },
            { name: 'San José', info: 'De las más antiguas, ¡conserva su clásico estilo!' },
            { name: 'Entre Ríos - Rodolfo Walsh', info: 'Estación en una famosa avenida, rinde homenaje al gran escritor.' },
            { name: 'Pichincha', info: 'Punto histórico donde había cines y teatros antiguos. 🎭' },
            { name: 'Jujuy', combinations: ['H'], info: '¡Acá podemos cambiar a la moderna línea amarilla! ✨' },
            { name: 'Gral. Urquiza', info: 'Bajo la plaza que fue el punto de partida de los antiguos trenes.' },
            { name: 'Boedo', info: 'El barrio del tango, la bohemia y mucha cultura porteña. 🎼' },
            { name: 'Avenida La Plata', info: 'Zona muy querida y cercana al lugar del Viejo Gasómetro. ⚽' },
            { name: 'José María Moreno', info: 'En homenaje a un importante prócer del país.' },
            { name: 'Emilio Mitre', info: 'Pasa por debajo del enorme y verde Parque Chacabuco. 🌳' },
            { name: 'Medalla Milagrosa', info: 'Muy cerca de una iglesia lindísima con ese nombre.' },
            { name: 'Varela', info: 'Un descanso de barrio antes de la gran cabecera.' },
            { name: 'Plaza de los Virreyes', combinations: ['P'], info: '¡El final del túnel! De acá podemos tomar el Premetro hasta arriba.' }
        ],
        'H': [
            { name: 'Facultad de Derecho' },
            { name: 'Las Heras' },
            { name: 'Santa Fe - Carlos Jáuregui', combinations: ['D'] },
            { name: 'Córdoba' },
            { name: 'Corrientes', combinations: ['B'] },
            { name: 'Once - 30 de Diciembre', combinations: ['A'], train: 'Sarmiento' },
            { name: 'Venezuela' },
            { name: 'Humberto I', combinations: ['E'] },
            { name: 'Inclán - Mezquita Al Ahmad' },
            { name: 'Caseros' },
            { name: 'Parque Patricios' },
            { name: 'Hospitales' }
        ],
        'P': [
            { name: 'Intendente Saguier', combinations: ['E'] },
            { name: 'Balbastro' },
            { name: 'Mariano Acosta' },
            { name: 'Somellera' },
            { name: 'Ana María Janer' },
            { name: 'Nuestra Señora de Fátima' },
            { name: 'Fernández de la Cruz' },
            { name: 'Presidente Illia', train: 'Belgrano Sur' },
            { name: 'Parque de la Ciudad' },
            { name: 'Cecilia Grierson' },
            { name: 'Escalada' },
            { name: 'Pola' },
            { name: 'Centro Cívico Lugano' },
            { name: 'General Savio' }
        ]
    },
    trainModels: [
        {
            id: 'CNR-Citic',
            name: 'CNR-Citic 200',
            origin: 'China',
            year: '2013-2016',
            air: true,
            lines: ['A', 'C'],
            image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAs9eZdgMkkFLfGAIeVJ3UZdG9h6HDMZh8aDHw9CdLfjHdwnklEF9_rRPvQmEmaUQy7wVP-swouFfVB_4Ns80m3Fg9V-D93TWAAu1p98YlHWhw_PZj9Vwf2w-lfGSIl1mYsZ8W3AFMGqdH2Tuc8HfWCYuXHy5ej5IlXuxlkHyg4TEYRr_3b2uGdzfwRGNcfaMIUZ19aldxg8nOcsvW9iz59hqU4a4jCpcigdtDuQFqKr7KhqZdrjCdzxAm_mnXOgAEeFkBijW9tXjo',
            blueprint: 'assets/cnr_citic.png',
            description: 'Trenes modernos fabricados en China. Tienen aire acondicionado y son de color gris con franjas de colores.',
            speed: '80 km/h',
            capacity: '1200 pasajeros',
            funFact: '¡Fueron los encargados de jubilar a los legendarios trenes de madera belgas en la Línea A! 🚇'
        },
        {
            id: 'Mitsubishi',
            name: 'Mitsubishi Eika 500',
            origin: 'Japón',
            year: '1954/1995',
            air: false,
            lines: ['B'],
            image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAm57c12RhpgOdonZs84d0JfA9L-kgIMwQ93Q52M7HPheeOOYxMxN8zYjrJI28q3KrU9AsarjzbsvC8oeFQgLPpyF1Xa_MWYyDVFLcdeDDUFS4zkpNd0Xnviam22H2sXjTA7Z7PMFYGUkQLthkVSeI3d8sI5mmi2RlOHk22ai-bep563TszqGQv7eBbfLIcfFSBzK_xG4ulf2vCCEKDpPY-pPFfNGBQwt5d0-UYORnSUmDG11jwYq-s4UZgR9Fd2UD18d9bB1T0iys',
            blueprint: 'assets/mitsubishi.png',
            description: 'Un clásico del subte porteño. Vinieron usados de la línea Marunouchi de Tokio. Son de color rojo brillante.',
            speed: '65 km/h',
            capacity: '1000 pasajeros',
            funFact: '¡Si prestás atención adentro seguro encontrás algún cartel original en japonés que quedó oculto! 🇯🇵'
        },
        {
            id: 'Alstom 300',
            name: 'Alstom Metropolis 300',
            origin: 'Brasil / Francia',
            year: '2015-2019',
            air: true,
            lines: ['D', 'H'],
            image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAs9eZdgMkkFLfGAIeVJ3UZdG9h6HDMZh8aDHw9CdLfjHdwnklEF9_rRPvQmEmaUQy7wVP-swouFfVB_4Ns80m3Fg9V-D93TWAAu1p98YlHWhw_PZj9Vwf2w-lfGSIl1mYsZ8W3AFMGqdH2Tuc8HfWCYuXHy5ej5IlXuxlkHyg4TEYRr_3b2uGdzfwRGNcfaMIUZ19aldxg8nOcsvW9iz59hqU4a4jCpcigdtDuQFqKr7KhqZdrjCdzxAm_mnXOgAEeFkBijW9tXjo',
            blueprint: 'assets/alstom_300.png',
            description: 'Los trenes más modernos y cómodos. Silenciosos y con aire acondicionado.',
            speed: '80 km/h',
            capacity: '1500 pasajeros',
            funFact: '¡Son tan largos que por dentro podés caminar desde el primer vagón hasta el último sin problemas! 🚶'
        },
        {
            id: 'Fiat Materfer',
            name: 'Fiat Materfer',
            origin: 'Argentina',
            year: '1980s',
            air: false,
            lines: ['E', 'A'],
            image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCDAItS5zzICpXbnLb8LxVpaGSaz-iAaK_oOv2URjVSJGFpcRW88AYhULaHleuMR7X4Yvkyimrn780t2izSzebdEuXkF_EIa2Z4wP9klwpFl-pkoA65pS97sS_ad_eNx9y2Rf0HqHlR7lDtqc_5dUlWEvauxOLnvZ6twZOh5iV0YItt1gPyQYgW7YHk-0a-OYED4z3ejGEoLHihFMuKcjv7ZvSU5wMl0U6IHc_zu5fLpIVJoYsI4SmYpO7DcBqaIhfzkTXCAzcyvsA',
            blueprint: 'assets/materfer.png',
            description: 'Fabricados en la planta Materfer de Córdoba. Son un orgullo nacional que sigue funcionando.',
            speed: '60 km/h',
            capacity: '1100 pasajeros',
            funFact: '¡A los maquinistas les encantan porque son como de la vieja escuela y súper duros para manejar! 🦾'
        }
    ]
};
